## 1) Calculation sample with torch

In [ ]:
import torch

In [31]:
# model parameters
w_1 = torch.tensor([0.23], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

# inputs and target
x_1 = torch.tensor([1.23])
y = torch.tensor([1.])

In [32]:
# calculate u and z
u = x_1 * w_1
z = u + b
print(z)

tensor([0.3829], grad_fn=<AddBackward0>)


In [33]:
# calculate sigmoid
a = torch.sigmoid(z)
print(a)

tensor([0.5946], grad_fn=<SigmoidBackward0>)


In [34]:
# calculate loss
import torch.nn.functional as F

# it's not best practice to use the binary_cross_entropy for loss
# l = F.binary_cross_entropy(a, y)

l = F.binary_cross_entropy_with_logits(z, y)
print(l)

tensor(0.5199, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [35]:
# calculate partial derivative of L and w1
# from torch.autograd import grad

# grad_L_w1 = grad(l, w_1, retain_graph=True)
# print(grad_L_w1)

# grad_L_b = grad(l, b, retain_graph=True)
# print(grad_L_b)

# instead of above code, we can use below short way
l.backward()
print(w_1.grad)
print(b.grad)

tensor([-0.4987])
tensor([-0.4054])


## 2) Neural Network Layers

In [38]:
import torch

# it will return the same results in each execution
torch.manual_seed(123)

linear = torch.nn.Linear(in_features=2, out_features=1)

In [41]:
print(linear.weight)

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)


In [42]:
print(linear.bias)

Parameter containing:
tensor([-0.3512], requires_grad=True)


In [44]:
x = torch.tensor([[1.2, 0.5]])
print(x)

tensor([[1.2000, 0.5000]])


In [45]:
w = linear.weight.detach()
b = linear.bias.detach()
z = x.matmul(w.T) + b

print(z)

tensor([[-0.6855]])


In [49]:
# we can write in a short form the above code
z = linear(x)
# the result will be the same as the previous code sample
print(z)

tensor([[-0.6855]], grad_fn=<AddmmBackward0>)
